### ISSUE TITLE
Borders still appear when width adjusted to zero

### ISSUE THREAD

**Issue by zchtodd** [PhotonDesigner/photon-designer#1] opened 2024-02-26 12:24 UTC
Although the border did eventually appear to respect the border width setting, it seems like there might be a sync issue between what the right pane shows and what the results are.

The border width is initially shown as zero when the actual border width is not zero.  On entering a different width, it seems like I need to click into and out of the text input a few times for it to be applied.

**Comment by tomdekan** [comment] 2024-03-12 18:05
I think that this issue was caused by showing the empty page div border. I've added a dashed line to the empty page div border to emphasise this. Will close this ticket. Will open another ticket if this point is still unclear.

**Closed** 2024-03-12 18:05 UTC
Labels: bug
